//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia_.Pablo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.sa/", ConfigurationName="Pablo.WSFarmacia11")]
    public interface WSFarmacia11 {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/cancelar_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/cancelar_pedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.cancelar_pedidoResponse cancelar_pedido(Farmacia_.Pablo.cancelar_pedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/cancelar_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/cancelar_pedidoResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.cancelar_pedidoResponse> cancelar_pedidoAsync(Farmacia_.Pablo.cancelar_pedidoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/verificar_existenciaRequest", ReplyAction="http://webservices.sa/WSFarmacia11/verificar_existenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.verificar_existenciaResponse verificar_existencia(Farmacia_.Pablo.verificar_existenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/verificar_existenciaRequest", ReplyAction="http://webservices.sa/WSFarmacia11/verificar_existenciaResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.verificar_existenciaResponse> verificar_existenciaAsync(Farmacia_.Pablo.verificar_existenciaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/agregar_detalle_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/agregar_detalle_pedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.agregar_detalle_pedidoResponse agregar_detalle_pedido(Farmacia_.Pablo.agregar_detalle_pedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/agregar_detalle_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/agregar_detalle_pedidoResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_detalle_pedidoResponse> agregar_detalle_pedidoAsync(Farmacia_.Pablo.agregar_detalle_pedidoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/agregar_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/agregar_pedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.agregar_pedidoResponse agregar_pedido(Farmacia_.Pablo.agregar_pedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/agregar_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/agregar_pedidoResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_pedidoResponse> agregar_pedidoAsync(Farmacia_.Pablo.agregar_pedidoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/agregar_productoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/agregar_productoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.agregar_productoResponse agregar_producto(Farmacia_.Pablo.agregar_productoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/agregar_productoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/agregar_productoResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_productoResponse> agregar_productoAsync(Farmacia_.Pablo.agregar_productoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/consultar_catalogo_clientesRequest", ReplyAction="http://webservices.sa/WSFarmacia11/consultar_catalogo_clientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.consultar_catalogo_clientesResponse consultar_catalogo_clientes(Farmacia_.Pablo.consultar_catalogo_clientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/consultar_catalogo_clientesRequest", ReplyAction="http://webservices.sa/WSFarmacia11/consultar_catalogo_clientesResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.consultar_catalogo_clientesResponse> consultar_catalogo_clientesAsync(Farmacia_.Pablo.consultar_catalogo_clientesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/consultar_catalogo_medicamentosRequest", ReplyAction="http://webservices.sa/WSFarmacia11/consultar_catalogo_medicamentosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.consultar_catalogo_medicamentosResponse consultar_catalogo_medicamentos(Farmacia_.Pablo.consultar_catalogo_medicamentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/consultar_catalogo_medicamentosRequest", ReplyAction="http://webservices.sa/WSFarmacia11/consultar_catalogo_medicamentosResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.consultar_catalogo_medicamentosResponse> consultar_catalogo_medicamentosAsync(Farmacia_.Pablo.consultar_catalogo_medicamentosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/buscar_clienteRequest", ReplyAction="http://webservices.sa/WSFarmacia11/buscar_clienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.buscar_clienteResponse buscar_cliente(Farmacia_.Pablo.buscar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/buscar_clienteRequest", ReplyAction="http://webservices.sa/WSFarmacia11/buscar_clienteResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.buscar_clienteResponse> buscar_clienteAsync(Farmacia_.Pablo.buscar_clienteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/obtener_pedidosRequest", ReplyAction="http://webservices.sa/WSFarmacia11/obtener_pedidosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.obtener_pedidosResponse obtener_pedidos(Farmacia_.Pablo.obtener_pedidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/obtener_pedidosRequest", ReplyAction="http://webservices.sa/WSFarmacia11/obtener_pedidosResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.obtener_pedidosResponse> obtener_pedidosAsync(Farmacia_.Pablo.obtener_pedidosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/obtener_detalle_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/obtener_detalle_pedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.obtener_detalle_pedidoResponse obtener_detalle_pedido(Farmacia_.Pablo.obtener_detalle_pedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/obtener_detalle_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/obtener_detalle_pedidoResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.obtener_detalle_pedidoResponse> obtener_detalle_pedidoAsync(Farmacia_.Pablo.obtener_detalle_pedidoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/pagar_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/pagar_pedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.pagar_pedidoResponse pagar_pedido(Farmacia_.Pablo.pagar_pedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/pagar_pedidoRequest", ReplyAction="http://webservices.sa/WSFarmacia11/pagar_pedidoResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.pagar_pedidoResponse> pagar_pedidoAsync(Farmacia_.Pablo.pagar_pedidoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/agregar_clienteRequest", ReplyAction="http://webservices.sa/WSFarmacia11/agregar_clienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Farmacia_.Pablo.agregar_clienteResponse agregar_cliente(Farmacia_.Pablo.agregar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sa/WSFarmacia11/agregar_clienteRequest", ReplyAction="http://webservices.sa/WSFarmacia11/agregar_clienteResponse")]
        System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_clienteResponse> agregar_clienteAsync(Farmacia_.Pablo.agregar_clienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelar_pedido", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class cancelar_pedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPedido;
        
        public cancelar_pedidoRequest() {
        }
        
        public cancelar_pedidoRequest(int idPedido) {
            this.idPedido = idPedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelar_pedidoResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class cancelar_pedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public cancelar_pedidoResponse() {
        }
        
        public cancelar_pedidoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificar_existencia", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class verificar_existenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        public verificar_existenciaRequest() {
        }
        
        public verificar_existenciaRequest(int idProducto, int cantidad) {
            this.idProducto = idProducto;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificar_existenciaResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class verificar_existenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public verificar_existenciaResponse() {
        }
        
        public verificar_existenciaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregar_detalle_pedido", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class agregar_detalle_pedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        public agregar_detalle_pedidoRequest() {
        }
        
        public agregar_detalle_pedidoRequest(int idPedido, int idProducto, int cantidad) {
            this.idPedido = idPedido;
            this.idProducto = idProducto;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregar_detalle_pedidoResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class agregar_detalle_pedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public agregar_detalle_pedidoResponse() {
        }
        
        public agregar_detalle_pedidoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregar_pedido", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class agregar_pedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCallCenter;
        
        public agregar_pedidoRequest() {
        }
        
        public agregar_pedidoRequest(int idCliente, int idCallCenter) {
            this.idCliente = idCliente;
            this.idCallCenter = idCallCenter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregar_pedidoResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class agregar_pedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public agregar_pedidoResponse() {
        }
        
        public agregar_pedidoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregar_producto", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class agregar_productoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        public agregar_productoRequest() {
        }
        
        public agregar_productoRequest(string nombre, double precio, string descripcion, int cantidad) {
            this.nombre = nombre;
            this.precio = precio;
            this.descripcion = descripcion;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregar_productoResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class agregar_productoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public agregar_productoResponse() {
        }
        
        public agregar_productoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sa/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private int idField;
        
        private string nitField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sa/")]
    public partial class pago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double subtotalField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sa/")]
    public partial class pedido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clienteField;
        
        private string direccionField;
        
        private string estadoField;
        
        private string fechaField;
        
        private int idField;
        
        private string nitField;
        
        private double subTotalField;
        
        private string tipoPagoField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double subTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
                this.RaisePropertyChanged("subTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
                this.RaisePropertyChanged("tipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sa/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        private double precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar_catalogo_clientes", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class consultar_catalogo_clientesRequest {
        
        public consultar_catalogo_clientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar_catalogo_clientesResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class consultar_catalogo_clientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Farmacia_.Pablo.cliente[] @return;
        
        public consultar_catalogo_clientesResponse() {
        }
        
        public consultar_catalogo_clientesResponse(Farmacia_.Pablo.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar_catalogo_medicamentos", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class consultar_catalogo_medicamentosRequest {
        
        public consultar_catalogo_medicamentosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar_catalogo_medicamentosResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class consultar_catalogo_medicamentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Farmacia_.Pablo.producto[] @return;
        
        public consultar_catalogo_medicamentosResponse() {
        }
        
        public consultar_catalogo_medicamentosResponse(Farmacia_.Pablo.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscar_cliente", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class buscar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nit;
        
        public buscar_clienteRequest() {
        }
        
        public buscar_clienteRequest(string nit) {
            this.nit = nit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscar_clienteResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class buscar_clienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Farmacia_.Pablo.cliente @return;
        
        public buscar_clienteResponse() {
        }
        
        public buscar_clienteResponse(Farmacia_.Pablo.cliente @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_pedidos", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class obtener_pedidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPedido;
        
        public obtener_pedidosRequest() {
        }
        
        public obtener_pedidosRequest(int idPedido) {
            this.idPedido = idPedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_pedidosResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class obtener_pedidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Farmacia_.Pablo.pedido[] @return;
        
        public obtener_pedidosResponse() {
        }
        
        public obtener_pedidosResponse(Farmacia_.Pablo.pedido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_detalle_pedido", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class obtener_detalle_pedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPedido;
        
        public obtener_detalle_pedidoRequest() {
        }
        
        public obtener_detalle_pedidoRequest(int idPedido) {
            this.idPedido = idPedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtener_detalle_pedidoResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class obtener_detalle_pedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Farmacia_.Pablo.pedido[] @return;
        
        public obtener_detalle_pedidoResponse() {
        }
        
        public obtener_detalle_pedidoResponse(Farmacia_.Pablo.pedido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pagar_pedido", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class pagar_pedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipoPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool decrementar;
        
        public pagar_pedidoRequest() {
        }
        
        public pagar_pedidoRequest(int idPedido, int tipoPago, bool decrementar) {
            this.idPedido = idPedido;
            this.tipoPago = tipoPago;
            this.decrementar = decrementar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pagar_pedidoResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class pagar_pedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Farmacia_.Pablo.pago @return;
        
        public pagar_pedidoResponse() {
        }
        
        public pagar_pedidoResponse(Farmacia_.Pablo.pago @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregar_cliente", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class agregar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        public agregar_clienteRequest() {
        }
        
        public agregar_clienteRequest(string nombre, string direccion, string nit, string telefono) {
            this.nombre = nombre;
            this.direccion = direccion;
            this.nit = nit;
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregar_clienteResponse", WrapperNamespace="http://webservices.sa/", IsWrapped=true)]
    public partial class agregar_clienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public agregar_clienteResponse() {
        }
        
        public agregar_clienteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSFarmacia11Channel : Farmacia_.Pablo.WSFarmacia11, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSFarmacia11Client : System.ServiceModel.ClientBase<Farmacia_.Pablo.WSFarmacia11>, Farmacia_.Pablo.WSFarmacia11 {
        
        public WSFarmacia11Client() {
        }
        
        public WSFarmacia11Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSFarmacia11Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFarmacia11Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFarmacia11Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.cancelar_pedidoResponse Farmacia_.Pablo.WSFarmacia11.cancelar_pedido(Farmacia_.Pablo.cancelar_pedidoRequest request) {
            return base.Channel.cancelar_pedido(request);
        }
        
        public bool cancelar_pedido(int idPedido) {
            Farmacia_.Pablo.cancelar_pedidoRequest inValue = new Farmacia_.Pablo.cancelar_pedidoRequest();
            inValue.idPedido = idPedido;
            Farmacia_.Pablo.cancelar_pedidoResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).cancelar_pedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.cancelar_pedidoResponse> Farmacia_.Pablo.WSFarmacia11.cancelar_pedidoAsync(Farmacia_.Pablo.cancelar_pedidoRequest request) {
            return base.Channel.cancelar_pedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.cancelar_pedidoResponse> cancelar_pedidoAsync(int idPedido) {
            Farmacia_.Pablo.cancelar_pedidoRequest inValue = new Farmacia_.Pablo.cancelar_pedidoRequest();
            inValue.idPedido = idPedido;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).cancelar_pedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.verificar_existenciaResponse Farmacia_.Pablo.WSFarmacia11.verificar_existencia(Farmacia_.Pablo.verificar_existenciaRequest request) {
            return base.Channel.verificar_existencia(request);
        }
        
        public bool verificar_existencia(int idProducto, int cantidad) {
            Farmacia_.Pablo.verificar_existenciaRequest inValue = new Farmacia_.Pablo.verificar_existenciaRequest();
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            Farmacia_.Pablo.verificar_existenciaResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).verificar_existencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.verificar_existenciaResponse> Farmacia_.Pablo.WSFarmacia11.verificar_existenciaAsync(Farmacia_.Pablo.verificar_existenciaRequest request) {
            return base.Channel.verificar_existenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.verificar_existenciaResponse> verificar_existenciaAsync(int idProducto, int cantidad) {
            Farmacia_.Pablo.verificar_existenciaRequest inValue = new Farmacia_.Pablo.verificar_existenciaRequest();
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).verificar_existenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.agregar_detalle_pedidoResponse Farmacia_.Pablo.WSFarmacia11.agregar_detalle_pedido(Farmacia_.Pablo.agregar_detalle_pedidoRequest request) {
            return base.Channel.agregar_detalle_pedido(request);
        }
        
        public bool agregar_detalle_pedido(int idPedido, int idProducto, int cantidad) {
            Farmacia_.Pablo.agregar_detalle_pedidoRequest inValue = new Farmacia_.Pablo.agregar_detalle_pedidoRequest();
            inValue.idPedido = idPedido;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            Farmacia_.Pablo.agregar_detalle_pedidoResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).agregar_detalle_pedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_detalle_pedidoResponse> Farmacia_.Pablo.WSFarmacia11.agregar_detalle_pedidoAsync(Farmacia_.Pablo.agregar_detalle_pedidoRequest request) {
            return base.Channel.agregar_detalle_pedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_detalle_pedidoResponse> agregar_detalle_pedidoAsync(int idPedido, int idProducto, int cantidad) {
            Farmacia_.Pablo.agregar_detalle_pedidoRequest inValue = new Farmacia_.Pablo.agregar_detalle_pedidoRequest();
            inValue.idPedido = idPedido;
            inValue.idProducto = idProducto;
            inValue.cantidad = cantidad;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).agregar_detalle_pedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.agregar_pedidoResponse Farmacia_.Pablo.WSFarmacia11.agregar_pedido(Farmacia_.Pablo.agregar_pedidoRequest request) {
            return base.Channel.agregar_pedido(request);
        }
        
        public int agregar_pedido(int idCliente, int idCallCenter) {
            Farmacia_.Pablo.agregar_pedidoRequest inValue = new Farmacia_.Pablo.agregar_pedidoRequest();
            inValue.idCliente = idCliente;
            inValue.idCallCenter = idCallCenter;
            Farmacia_.Pablo.agregar_pedidoResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).agregar_pedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_pedidoResponse> Farmacia_.Pablo.WSFarmacia11.agregar_pedidoAsync(Farmacia_.Pablo.agregar_pedidoRequest request) {
            return base.Channel.agregar_pedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_pedidoResponse> agregar_pedidoAsync(int idCliente, int idCallCenter) {
            Farmacia_.Pablo.agregar_pedidoRequest inValue = new Farmacia_.Pablo.agregar_pedidoRequest();
            inValue.idCliente = idCliente;
            inValue.idCallCenter = idCallCenter;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).agregar_pedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.agregar_productoResponse Farmacia_.Pablo.WSFarmacia11.agregar_producto(Farmacia_.Pablo.agregar_productoRequest request) {
            return base.Channel.agregar_producto(request);
        }
        
        public bool agregar_producto(string nombre, double precio, string descripcion, int cantidad) {
            Farmacia_.Pablo.agregar_productoRequest inValue = new Farmacia_.Pablo.agregar_productoRequest();
            inValue.nombre = nombre;
            inValue.precio = precio;
            inValue.descripcion = descripcion;
            inValue.cantidad = cantidad;
            Farmacia_.Pablo.agregar_productoResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).agregar_producto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_productoResponse> Farmacia_.Pablo.WSFarmacia11.agregar_productoAsync(Farmacia_.Pablo.agregar_productoRequest request) {
            return base.Channel.agregar_productoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_productoResponse> agregar_productoAsync(string nombre, double precio, string descripcion, int cantidad) {
            Farmacia_.Pablo.agregar_productoRequest inValue = new Farmacia_.Pablo.agregar_productoRequest();
            inValue.nombre = nombre;
            inValue.precio = precio;
            inValue.descripcion = descripcion;
            inValue.cantidad = cantidad;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).agregar_productoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.consultar_catalogo_clientesResponse Farmacia_.Pablo.WSFarmacia11.consultar_catalogo_clientes(Farmacia_.Pablo.consultar_catalogo_clientesRequest request) {
            return base.Channel.consultar_catalogo_clientes(request);
        }
        
        public Farmacia_.Pablo.cliente[] consultar_catalogo_clientes() {
            Farmacia_.Pablo.consultar_catalogo_clientesRequest inValue = new Farmacia_.Pablo.consultar_catalogo_clientesRequest();
            Farmacia_.Pablo.consultar_catalogo_clientesResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).consultar_catalogo_clientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.consultar_catalogo_clientesResponse> Farmacia_.Pablo.WSFarmacia11.consultar_catalogo_clientesAsync(Farmacia_.Pablo.consultar_catalogo_clientesRequest request) {
            return base.Channel.consultar_catalogo_clientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.consultar_catalogo_clientesResponse> consultar_catalogo_clientesAsync() {
            Farmacia_.Pablo.consultar_catalogo_clientesRequest inValue = new Farmacia_.Pablo.consultar_catalogo_clientesRequest();
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).consultar_catalogo_clientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.consultar_catalogo_medicamentosResponse Farmacia_.Pablo.WSFarmacia11.consultar_catalogo_medicamentos(Farmacia_.Pablo.consultar_catalogo_medicamentosRequest request) {
            return base.Channel.consultar_catalogo_medicamentos(request);
        }
        
        public Farmacia_.Pablo.producto[] consultar_catalogo_medicamentos() {
            Farmacia_.Pablo.consultar_catalogo_medicamentosRequest inValue = new Farmacia_.Pablo.consultar_catalogo_medicamentosRequest();
            Farmacia_.Pablo.consultar_catalogo_medicamentosResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).consultar_catalogo_medicamentos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.consultar_catalogo_medicamentosResponse> Farmacia_.Pablo.WSFarmacia11.consultar_catalogo_medicamentosAsync(Farmacia_.Pablo.consultar_catalogo_medicamentosRequest request) {
            return base.Channel.consultar_catalogo_medicamentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.consultar_catalogo_medicamentosResponse> consultar_catalogo_medicamentosAsync() {
            Farmacia_.Pablo.consultar_catalogo_medicamentosRequest inValue = new Farmacia_.Pablo.consultar_catalogo_medicamentosRequest();
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).consultar_catalogo_medicamentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.buscar_clienteResponse Farmacia_.Pablo.WSFarmacia11.buscar_cliente(Farmacia_.Pablo.buscar_clienteRequest request) {
            return base.Channel.buscar_cliente(request);
        }
        
        public Farmacia_.Pablo.cliente buscar_cliente(string nit) {
            Farmacia_.Pablo.buscar_clienteRequest inValue = new Farmacia_.Pablo.buscar_clienteRequest();
            inValue.nit = nit;
            Farmacia_.Pablo.buscar_clienteResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).buscar_cliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.buscar_clienteResponse> Farmacia_.Pablo.WSFarmacia11.buscar_clienteAsync(Farmacia_.Pablo.buscar_clienteRequest request) {
            return base.Channel.buscar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.buscar_clienteResponse> buscar_clienteAsync(string nit) {
            Farmacia_.Pablo.buscar_clienteRequest inValue = new Farmacia_.Pablo.buscar_clienteRequest();
            inValue.nit = nit;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).buscar_clienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.obtener_pedidosResponse Farmacia_.Pablo.WSFarmacia11.obtener_pedidos(Farmacia_.Pablo.obtener_pedidosRequest request) {
            return base.Channel.obtener_pedidos(request);
        }
        
        public Farmacia_.Pablo.pedido[] obtener_pedidos(int idPedido) {
            Farmacia_.Pablo.obtener_pedidosRequest inValue = new Farmacia_.Pablo.obtener_pedidosRequest();
            inValue.idPedido = idPedido;
            Farmacia_.Pablo.obtener_pedidosResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).obtener_pedidos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.obtener_pedidosResponse> Farmacia_.Pablo.WSFarmacia11.obtener_pedidosAsync(Farmacia_.Pablo.obtener_pedidosRequest request) {
            return base.Channel.obtener_pedidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.obtener_pedidosResponse> obtener_pedidosAsync(int idPedido) {
            Farmacia_.Pablo.obtener_pedidosRequest inValue = new Farmacia_.Pablo.obtener_pedidosRequest();
            inValue.idPedido = idPedido;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).obtener_pedidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.obtener_detalle_pedidoResponse Farmacia_.Pablo.WSFarmacia11.obtener_detalle_pedido(Farmacia_.Pablo.obtener_detalle_pedidoRequest request) {
            return base.Channel.obtener_detalle_pedido(request);
        }
        
        public Farmacia_.Pablo.pedido[] obtener_detalle_pedido(int idPedido) {
            Farmacia_.Pablo.obtener_detalle_pedidoRequest inValue = new Farmacia_.Pablo.obtener_detalle_pedidoRequest();
            inValue.idPedido = idPedido;
            Farmacia_.Pablo.obtener_detalle_pedidoResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).obtener_detalle_pedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.obtener_detalle_pedidoResponse> Farmacia_.Pablo.WSFarmacia11.obtener_detalle_pedidoAsync(Farmacia_.Pablo.obtener_detalle_pedidoRequest request) {
            return base.Channel.obtener_detalle_pedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.obtener_detalle_pedidoResponse> obtener_detalle_pedidoAsync(int idPedido) {
            Farmacia_.Pablo.obtener_detalle_pedidoRequest inValue = new Farmacia_.Pablo.obtener_detalle_pedidoRequest();
            inValue.idPedido = idPedido;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).obtener_detalle_pedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.pagar_pedidoResponse Farmacia_.Pablo.WSFarmacia11.pagar_pedido(Farmacia_.Pablo.pagar_pedidoRequest request) {
            return base.Channel.pagar_pedido(request);
        }
        
        public Farmacia_.Pablo.pago pagar_pedido(int idPedido, int tipoPago, bool decrementar) {
            Farmacia_.Pablo.pagar_pedidoRequest inValue = new Farmacia_.Pablo.pagar_pedidoRequest();
            inValue.idPedido = idPedido;
            inValue.tipoPago = tipoPago;
            inValue.decrementar = decrementar;
            Farmacia_.Pablo.pagar_pedidoResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).pagar_pedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.pagar_pedidoResponse> Farmacia_.Pablo.WSFarmacia11.pagar_pedidoAsync(Farmacia_.Pablo.pagar_pedidoRequest request) {
            return base.Channel.pagar_pedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.pagar_pedidoResponse> pagar_pedidoAsync(int idPedido, int tipoPago, bool decrementar) {
            Farmacia_.Pablo.pagar_pedidoRequest inValue = new Farmacia_.Pablo.pagar_pedidoRequest();
            inValue.idPedido = idPedido;
            inValue.tipoPago = tipoPago;
            inValue.decrementar = decrementar;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).pagar_pedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Pablo.agregar_clienteResponse Farmacia_.Pablo.WSFarmacia11.agregar_cliente(Farmacia_.Pablo.agregar_clienteRequest request) {
            return base.Channel.agregar_cliente(request);
        }
        
        public bool agregar_cliente(string nombre, string direccion, string nit, string telefono) {
            Farmacia_.Pablo.agregar_clienteRequest inValue = new Farmacia_.Pablo.agregar_clienteRequest();
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.nit = nit;
            inValue.telefono = telefono;
            Farmacia_.Pablo.agregar_clienteResponse retVal = ((Farmacia_.Pablo.WSFarmacia11)(this)).agregar_cliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_clienteResponse> Farmacia_.Pablo.WSFarmacia11.agregar_clienteAsync(Farmacia_.Pablo.agregar_clienteRequest request) {
            return base.Channel.agregar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Pablo.agregar_clienteResponse> agregar_clienteAsync(string nombre, string direccion, string nit, string telefono) {
            Farmacia_.Pablo.agregar_clienteRequest inValue = new Farmacia_.Pablo.agregar_clienteRequest();
            inValue.nombre = nombre;
            inValue.direccion = direccion;
            inValue.nit = nit;
            inValue.telefono = telefono;
            return ((Farmacia_.Pablo.WSFarmacia11)(this)).agregar_clienteAsync(inValue);
        }
    }
}
