//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia_.ws {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codigo_productos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_compra", ReplyAction="*")]
        Farmacia_.ws.registrar_compraResponse registrar_compra(Farmacia_.ws.registrar_compraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_compra", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.ws.registrar_compraResponse> registrar_compraAsync(Farmacia_.ws.registrar_compraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_pago", ReplyAction="*")]
        int registrar_pago(int codigo_farmacia, int codigo_cliente, int codigo_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_pago", ReplyAction="*")]
        System.Threading.Tasks.Task<int> registrar_pagoAsync(int codigo_farmacia, int codigo_cliente, int codigo_compra);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_cliente", ReplyAction="*")]
        Farmacia_.ws.registrar_clienteResponse registrar_cliente(Farmacia_.ws.registrar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.ws.registrar_clienteResponse> registrar_clienteAsync(Farmacia_.ws.registrar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_pedido", ReplyAction="*")]
        int registrar_pedido(int codigo_tienda, int codigo_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_pedido", ReplyAction="*")]
        System.Threading.Tasks.Task<int> registrar_pedidoAsync(int codigo_tienda, int codigo_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelar_pedido", ReplyAction="*")]
        bool cancelar_pedido(int codigo_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelar_pedido", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> cancelar_pedidoAsync(int codigo_compra);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nit del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_cliente", ReplyAction="*")]
        Farmacia_.ws.consultar_clienteResponse consultar_cliente(Farmacia_.ws.consultar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.ws.consultar_clienteResponse> consultar_clienteAsync(Farmacia_.ws.consultar_clienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultar_medicamentosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_medicamentos", ReplyAction="*")]
        Farmacia_.ws.consultar_medicamentosResponse consultar_medicamentos(Farmacia_.ws.consultar_medicamentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_medicamentos", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.ws.consultar_medicamentosResponse> consultar_medicamentosAsync(Farmacia_.ws.consultar_medicamentosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultar_farmaciasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_farmacias", ReplyAction="*")]
        Farmacia_.ws.consultar_farmaciasResponse consultar_farmacias(Farmacia_.ws.consultar_farmaciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_farmacias", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.ws.consultar_farmaciasResponse> consultar_farmaciasAsync(Farmacia_.ws.consultar_farmaciasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultar_clientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_clientes", ReplyAction="*")]
        Farmacia_.ws.consultar_clientesResponse consultar_clientes(Farmacia_.ws.consultar_clientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_clientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.ws.consultar_clientesResponse> consultar_clientesAsync(Farmacia_.ws.consultar_clientesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrar_compraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar_compra", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.registrar_compraRequestBody Body;
        
        public registrar_compraRequest() {
        }
        
        public registrar_compraRequest(Farmacia_.ws.registrar_compraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrar_compraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigo_tienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigo_cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Farmacia_.ws.ArrayOfInt codigo_productos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Farmacia_.ws.ArrayOfInt unidades_productos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public char tipo_pago;
        
        public registrar_compraRequestBody() {
        }
        
        public registrar_compraRequestBody(int codigo_tienda, int codigo_cliente, Farmacia_.ws.ArrayOfInt codigo_productos, Farmacia_.ws.ArrayOfInt unidades_productos, char tipo_pago) {
            this.codigo_tienda = codigo_tienda;
            this.codigo_cliente = codigo_cliente;
            this.codigo_productos = codigo_productos;
            this.unidades_productos = unidades_productos;
            this.tipo_pago = tipo_pago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrar_compraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar_compraResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.registrar_compraResponseBody Body;
        
        public registrar_compraResponse() {
        }
        
        public registrar_compraResponse(Farmacia_.ws.registrar_compraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrar_compraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Farmacia_.ws.ArrayOfInt registrar_compraResult;
        
        public registrar_compraResponseBody() {
        }
        
        public registrar_compraResponseBody(Farmacia_.ws.ArrayOfInt registrar_compraResult) {
            this.registrar_compraResult = registrar_compraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar_cliente", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.registrar_clienteRequestBody Body;
        
        public registrar_clienteRequest() {
        }
        
        public registrar_clienteRequest(Farmacia_.ws.registrar_clienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrar_clienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int nit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string direccion;
        
        public registrar_clienteRequestBody() {
        }
        
        public registrar_clienteRequestBody(int nit, string nombre, string telefono, string direccion) {
            this.nit = nit;
            this.nombre = nombre;
            this.telefono = telefono;
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrar_clienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar_clienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.registrar_clienteResponseBody Body;
        
        public registrar_clienteResponse() {
        }
        
        public registrar_clienteResponse(Farmacia_.ws.registrar_clienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrar_clienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int registrar_clienteResult;
        
        public registrar_clienteResponseBody() {
        }
        
        public registrar_clienteResponseBody(int registrar_clienteResult) {
            this.registrar_clienteResult = registrar_clienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_cliente", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.consultar_clienteRequestBody Body;
        
        public consultar_clienteRequest() {
        }
        
        public consultar_clienteRequest(Farmacia_.ws.consultar_clienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_clienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nit;
        
        public consultar_clienteRequestBody() {
        }
        
        public consultar_clienteRequestBody(string nit) {
            this.nit = nit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_clienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_clienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.consultar_clienteResponseBody Body;
        
        public consultar_clienteResponse() {
        }
        
        public consultar_clienteResponse(Farmacia_.ws.consultar_clienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_clienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Farmacia_.ws.ArrayOfString consultar_clienteResult;
        
        public consultar_clienteResponseBody() {
        }
        
        public consultar_clienteResponseBody(Farmacia_.ws.ArrayOfString consultar_clienteResult) {
            this.consultar_clienteResult = consultar_clienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_medicamentosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_medicamentos", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.consultar_medicamentosRequestBody Body;
        
        public consultar_medicamentosRequest() {
        }
        
        public consultar_medicamentosRequest(Farmacia_.ws.consultar_medicamentosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_medicamentosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigo_farmacia;
        
        public consultar_medicamentosRequestBody() {
        }
        
        public consultar_medicamentosRequestBody(int codigo_farmacia) {
            this.codigo_farmacia = codigo_farmacia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_medicamentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_medicamentosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.consultar_medicamentosResponseBody Body;
        
        public consultar_medicamentosResponse() {
        }
        
        public consultar_medicamentosResponse(Farmacia_.ws.consultar_medicamentosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_medicamentosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Farmacia_.ws.ArrayOfString> consultar_medicamentosResult;
        
        public consultar_medicamentosResponseBody() {
        }
        
        public consultar_medicamentosResponseBody(System.Collections.Generic.List<Farmacia_.ws.ArrayOfString> consultar_medicamentosResult) {
            this.consultar_medicamentosResult = consultar_medicamentosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_farmaciasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_farmacias", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.consultar_farmaciasRequestBody Body;
        
        public consultar_farmaciasRequest() {
        }
        
        public consultar_farmaciasRequest(Farmacia_.ws.consultar_farmaciasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultar_farmaciasRequestBody {
        
        public consultar_farmaciasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_farmaciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_farmaciasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.consultar_farmaciasResponseBody Body;
        
        public consultar_farmaciasResponse() {
        }
        
        public consultar_farmaciasResponse(Farmacia_.ws.consultar_farmaciasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_farmaciasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Farmacia_.ws.ArrayOfString> consultar_farmaciasResult;
        
        public consultar_farmaciasResponseBody() {
        }
        
        public consultar_farmaciasResponseBody(System.Collections.Generic.List<Farmacia_.ws.ArrayOfString> consultar_farmaciasResult) {
            this.consultar_farmaciasResult = consultar_farmaciasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_clientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_clientes", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.consultar_clientesRequestBody Body;
        
        public consultar_clientesRequest() {
        }
        
        public consultar_clientesRequest(Farmacia_.ws.consultar_clientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultar_clientesRequestBody {
        
        public consultar_clientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_clientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_clientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.ws.consultar_clientesResponseBody Body;
        
        public consultar_clientesResponse() {
        }
        
        public consultar_clientesResponse(Farmacia_.ws.consultar_clientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_clientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Farmacia_.ws.ArrayOfString> consultar_clientesResult;
        
        public consultar_clientesResponseBody() {
        }
        
        public consultar_clientesResponseBody(System.Collections.Generic.List<Farmacia_.ws.ArrayOfString> consultar_clientesResult) {
            this.consultar_clientesResult = consultar_clientesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Farmacia_.ws.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Farmacia_.ws.ServiceSoap>, Farmacia_.ws.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.ws.registrar_compraResponse Farmacia_.ws.ServiceSoap.registrar_compra(Farmacia_.ws.registrar_compraRequest request) {
            return base.Channel.registrar_compra(request);
        }
        
        public Farmacia_.ws.ArrayOfInt registrar_compra(int codigo_tienda, int codigo_cliente, Farmacia_.ws.ArrayOfInt codigo_productos, Farmacia_.ws.ArrayOfInt unidades_productos, char tipo_pago) {
            Farmacia_.ws.registrar_compraRequest inValue = new Farmacia_.ws.registrar_compraRequest();
            inValue.Body = new Farmacia_.ws.registrar_compraRequestBody();
            inValue.Body.codigo_tienda = codigo_tienda;
            inValue.Body.codigo_cliente = codigo_cliente;
            inValue.Body.codigo_productos = codigo_productos;
            inValue.Body.unidades_productos = unidades_productos;
            inValue.Body.tipo_pago = tipo_pago;
            Farmacia_.ws.registrar_compraResponse retVal = ((Farmacia_.ws.ServiceSoap)(this)).registrar_compra(inValue);
            return retVal.Body.registrar_compraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.ws.registrar_compraResponse> Farmacia_.ws.ServiceSoap.registrar_compraAsync(Farmacia_.ws.registrar_compraRequest request) {
            return base.Channel.registrar_compraAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.ws.registrar_compraResponse> registrar_compraAsync(int codigo_tienda, int codigo_cliente, Farmacia_.ws.ArrayOfInt codigo_productos, Farmacia_.ws.ArrayOfInt unidades_productos, char tipo_pago) {
            Farmacia_.ws.registrar_compraRequest inValue = new Farmacia_.ws.registrar_compraRequest();
            inValue.Body = new Farmacia_.ws.registrar_compraRequestBody();
            inValue.Body.codigo_tienda = codigo_tienda;
            inValue.Body.codigo_cliente = codigo_cliente;
            inValue.Body.codigo_productos = codigo_productos;
            inValue.Body.unidades_productos = unidades_productos;
            inValue.Body.tipo_pago = tipo_pago;
            return ((Farmacia_.ws.ServiceSoap)(this)).registrar_compraAsync(inValue);
        }
        
        public int registrar_pago(int codigo_farmacia, int codigo_cliente, int codigo_compra) {
            return base.Channel.registrar_pago(codigo_farmacia, codigo_cliente, codigo_compra);
        }
        
        public System.Threading.Tasks.Task<int> registrar_pagoAsync(int codigo_farmacia, int codigo_cliente, int codigo_compra) {
            return base.Channel.registrar_pagoAsync(codigo_farmacia, codigo_cliente, codigo_compra);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.ws.registrar_clienteResponse Farmacia_.ws.ServiceSoap.registrar_cliente(Farmacia_.ws.registrar_clienteRequest request) {
            return base.Channel.registrar_cliente(request);
        }
        
        public int registrar_cliente(int nit, string nombre, string telefono, string direccion) {
            Farmacia_.ws.registrar_clienteRequest inValue = new Farmacia_.ws.registrar_clienteRequest();
            inValue.Body = new Farmacia_.ws.registrar_clienteRequestBody();
            inValue.Body.nit = nit;
            inValue.Body.nombre = nombre;
            inValue.Body.telefono = telefono;
            inValue.Body.direccion = direccion;
            Farmacia_.ws.registrar_clienteResponse retVal = ((Farmacia_.ws.ServiceSoap)(this)).registrar_cliente(inValue);
            return retVal.Body.registrar_clienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.ws.registrar_clienteResponse> Farmacia_.ws.ServiceSoap.registrar_clienteAsync(Farmacia_.ws.registrar_clienteRequest request) {
            return base.Channel.registrar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.ws.registrar_clienteResponse> registrar_clienteAsync(int nit, string nombre, string telefono, string direccion) {
            Farmacia_.ws.registrar_clienteRequest inValue = new Farmacia_.ws.registrar_clienteRequest();
            inValue.Body = new Farmacia_.ws.registrar_clienteRequestBody();
            inValue.Body.nit = nit;
            inValue.Body.nombre = nombre;
            inValue.Body.telefono = telefono;
            inValue.Body.direccion = direccion;
            return ((Farmacia_.ws.ServiceSoap)(this)).registrar_clienteAsync(inValue);
        }
        
        public int registrar_pedido(int codigo_tienda, int codigo_compra) {
            return base.Channel.registrar_pedido(codigo_tienda, codigo_compra);
        }
        
        public System.Threading.Tasks.Task<int> registrar_pedidoAsync(int codigo_tienda, int codigo_compra) {
            return base.Channel.registrar_pedidoAsync(codigo_tienda, codigo_compra);
        }
        
        public bool cancelar_pedido(int codigo_compra) {
            return base.Channel.cancelar_pedido(codigo_compra);
        }
        
        public System.Threading.Tasks.Task<bool> cancelar_pedidoAsync(int codigo_compra) {
            return base.Channel.cancelar_pedidoAsync(codigo_compra);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.ws.consultar_clienteResponse Farmacia_.ws.ServiceSoap.consultar_cliente(Farmacia_.ws.consultar_clienteRequest request) {
            return base.Channel.consultar_cliente(request);
        }
        
        public Farmacia_.ws.ArrayOfString consultar_cliente(string nit) {
            Farmacia_.ws.consultar_clienteRequest inValue = new Farmacia_.ws.consultar_clienteRequest();
            inValue.Body = new Farmacia_.ws.consultar_clienteRequestBody();
            inValue.Body.nit = nit;
            Farmacia_.ws.consultar_clienteResponse retVal = ((Farmacia_.ws.ServiceSoap)(this)).consultar_cliente(inValue);
            return retVal.Body.consultar_clienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.ws.consultar_clienteResponse> Farmacia_.ws.ServiceSoap.consultar_clienteAsync(Farmacia_.ws.consultar_clienteRequest request) {
            return base.Channel.consultar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.ws.consultar_clienteResponse> consultar_clienteAsync(string nit) {
            Farmacia_.ws.consultar_clienteRequest inValue = new Farmacia_.ws.consultar_clienteRequest();
            inValue.Body = new Farmacia_.ws.consultar_clienteRequestBody();
            inValue.Body.nit = nit;
            return ((Farmacia_.ws.ServiceSoap)(this)).consultar_clienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.ws.consultar_medicamentosResponse Farmacia_.ws.ServiceSoap.consultar_medicamentos(Farmacia_.ws.consultar_medicamentosRequest request) {
            return base.Channel.consultar_medicamentos(request);
        }
        
        public System.Collections.Generic.List<Farmacia_.ws.ArrayOfString> consultar_medicamentos(int codigo_farmacia) {
            Farmacia_.ws.consultar_medicamentosRequest inValue = new Farmacia_.ws.consultar_medicamentosRequest();
            inValue.Body = new Farmacia_.ws.consultar_medicamentosRequestBody();
            inValue.Body.codigo_farmacia = codigo_farmacia;
            Farmacia_.ws.consultar_medicamentosResponse retVal = ((Farmacia_.ws.ServiceSoap)(this)).consultar_medicamentos(inValue);
            return retVal.Body.consultar_medicamentosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.ws.consultar_medicamentosResponse> Farmacia_.ws.ServiceSoap.consultar_medicamentosAsync(Farmacia_.ws.consultar_medicamentosRequest request) {
            return base.Channel.consultar_medicamentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.ws.consultar_medicamentosResponse> consultar_medicamentosAsync(int codigo_farmacia) {
            Farmacia_.ws.consultar_medicamentosRequest inValue = new Farmacia_.ws.consultar_medicamentosRequest();
            inValue.Body = new Farmacia_.ws.consultar_medicamentosRequestBody();
            inValue.Body.codigo_farmacia = codigo_farmacia;
            return ((Farmacia_.ws.ServiceSoap)(this)).consultar_medicamentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.ws.consultar_farmaciasResponse Farmacia_.ws.ServiceSoap.consultar_farmacias(Farmacia_.ws.consultar_farmaciasRequest request) {
            return base.Channel.consultar_farmacias(request);
        }
        
        public System.Collections.Generic.List<Farmacia_.ws.ArrayOfString> consultar_farmacias() {
            Farmacia_.ws.consultar_farmaciasRequest inValue = new Farmacia_.ws.consultar_farmaciasRequest();
            inValue.Body = new Farmacia_.ws.consultar_farmaciasRequestBody();
            Farmacia_.ws.consultar_farmaciasResponse retVal = ((Farmacia_.ws.ServiceSoap)(this)).consultar_farmacias(inValue);
            return retVal.Body.consultar_farmaciasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.ws.consultar_farmaciasResponse> Farmacia_.ws.ServiceSoap.consultar_farmaciasAsync(Farmacia_.ws.consultar_farmaciasRequest request) {
            return base.Channel.consultar_farmaciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.ws.consultar_farmaciasResponse> consultar_farmaciasAsync() {
            Farmacia_.ws.consultar_farmaciasRequest inValue = new Farmacia_.ws.consultar_farmaciasRequest();
            inValue.Body = new Farmacia_.ws.consultar_farmaciasRequestBody();
            return ((Farmacia_.ws.ServiceSoap)(this)).consultar_farmaciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.ws.consultar_clientesResponse Farmacia_.ws.ServiceSoap.consultar_clientes(Farmacia_.ws.consultar_clientesRequest request) {
            return base.Channel.consultar_clientes(request);
        }
        
        public System.Collections.Generic.List<Farmacia_.ws.ArrayOfString> consultar_clientes() {
            Farmacia_.ws.consultar_clientesRequest inValue = new Farmacia_.ws.consultar_clientesRequest();
            inValue.Body = new Farmacia_.ws.consultar_clientesRequestBody();
            Farmacia_.ws.consultar_clientesResponse retVal = ((Farmacia_.ws.ServiceSoap)(this)).consultar_clientes(inValue);
            return retVal.Body.consultar_clientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.ws.consultar_clientesResponse> Farmacia_.ws.ServiceSoap.consultar_clientesAsync(Farmacia_.ws.consultar_clientesRequest request) {
            return base.Channel.consultar_clientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.ws.consultar_clientesResponse> consultar_clientesAsync() {
            Farmacia_.ws.consultar_clientesRequest inValue = new Farmacia_.ws.consultar_clientesRequest();
            inValue.Body = new Farmacia_.ws.consultar_clientesRequestBody();
            return ((Farmacia_.ws.ServiceSoap)(this)).consultar_clientesAsync(inValue);
        }
    }
}
