//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.36213
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia_.Servicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nit {
            get {
                return this.nitField;
            }
            set {
                if ((object.ReferenceEquals(this.nitField, value) != true)) {
                    this.nitField = value;
                    this.RaisePropertyChanged("nit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.id_clienteField, value) != true)) {
                    this.id_clienteField = value;
                    this.RaisePropertyChanged("id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfMedicamento", Namespace="http://tempuri.org/", ItemName="medicamento")]
    [System.SerializableAttribute()]
    public class ArrayOfMedicamento : System.Collections.Generic.List<Farmacia_.Servicio.medicamento> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="medicamento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class medicamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        private int cantidad_disponibleField;
        
        private int codigo_medicamentoField;
        
        private double precio_unitarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int cantidad_disponible {
            get {
                return this.cantidad_disponibleField;
            }
            set {
                if ((this.cantidad_disponibleField.Equals(value) != true)) {
                    this.cantidad_disponibleField = value;
                    this.RaisePropertyChanged("cantidad_disponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int codigo_medicamento {
            get {
                return this.codigo_medicamentoField;
            }
            set {
                if ((this.codigo_medicamentoField.Equals(value) != true)) {
                    this.codigo_medicamentoField = value;
                    this.RaisePropertyChanged("codigo_medicamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double precio_unitario {
            get {
                return this.precio_unitarioField;
            }
            set {
                if ((this.precio_unitarioField.Equals(value) != true)) {
                    this.precio_unitarioField = value;
                    this.RaisePropertyChanged("precio_unitario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfFarmacia", Namespace="http://tempuri.org/", ItemName="farmacia")]
    [System.SerializableAttribute()]
    public class ArrayOfFarmacia : System.Collections.Generic.List<Farmacia_.Servicio.farmacia> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="farmacia", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class farmacia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigo_farmaciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo_farmacia {
            get {
                return this.codigo_farmaciaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigo_farmaciaField, value) != true)) {
                    this.codigo_farmaciaField = value;
                    this.RaisePropertyChanged("codigo_farmacia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCliente", Namespace="http://tempuri.org/", ItemName="cliente")]
    [System.SerializableAttribute()]
    public class ArrayOfCliente : System.Collections.Generic.List<Farmacia_.Servicio.cliente> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfPedido", Namespace="http://tempuri.org/", ItemName="pedido")]
    [System.SerializableAttribute()]
    public class ArrayOfPedido : System.Collections.Generic.List<Farmacia_.Servicio.pedido> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pedido", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre_cliente {
            get {
                return this.nombre_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_clienteField, value) != true)) {
                    this.nombre_clienteField = value;
                    this.RaisePropertyChanged("nombre_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nit del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_cliente", ReplyAction="*")]
        Farmacia_.Servicio.consultar_clienteResponse consultar_cliente(Farmacia_.Servicio.consultar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_clienteResponse> consultar_clienteAsync(Farmacia_.Servicio.consultar_clienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultar_medicamentosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_medicamentos", ReplyAction="*")]
        Farmacia_.Servicio.consultar_medicamentosResponse consultar_medicamentos(Farmacia_.Servicio.consultar_medicamentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_medicamentos", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_medicamentosResponse> consultar_medicamentosAsync(Farmacia_.Servicio.consultar_medicamentosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultar_farmaciasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_farmacias", ReplyAction="*")]
        Farmacia_.Servicio.consultar_farmaciasResponse consultar_farmacias(Farmacia_.Servicio.consultar_farmaciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_farmacias", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_farmaciasResponse> consultar_farmaciasAsync(Farmacia_.Servicio.consultar_farmaciasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultar_clientesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_clientes", ReplyAction="*")]
        Farmacia_.Servicio.consultar_clientesResponse consultar_clientes(Farmacia_.Servicio.consultar_clientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_clientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_clientesResponse> consultar_clientesAsync(Farmacia_.Servicio.consultar_clientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento consultar_pedidosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_pedidos", ReplyAction="*")]
        Farmacia_.Servicio.consultar_pedidosResponse consultar_pedidos(Farmacia_.Servicio.consultar_pedidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultar_pedidos", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_pedidosResponse> consultar_pedidosAsync(Farmacia_.Servicio.consultar_pedidosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codigo_productos del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_compra", ReplyAction="*")]
        Farmacia_.Servicio.registrar_compraResponse registrar_compra(Farmacia_.Servicio.registrar_compraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_compra", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.Servicio.registrar_compraResponse> registrar_compraAsync(Farmacia_.Servicio.registrar_compraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_pago", ReplyAction="*")]
        int registrar_pago(int codigo_compra, int tipo_pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_pago", ReplyAction="*")]
        System.Threading.Tasks.Task<int> registrar_pagoAsync(int codigo_compra, int tipo_pago);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nit del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_cliente", ReplyAction="*")]
        Farmacia_.Servicio.registrar_clienteResponse registrar_cliente(Farmacia_.Servicio.registrar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Farmacia_.Servicio.registrar_clienteResponse> registrar_clienteAsync(Farmacia_.Servicio.registrar_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_pedido", ReplyAction="*")]
        int registrar_pedido(int codigo_farmacia, int codigo_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar_pedido", ReplyAction="*")]
        System.Threading.Tasks.Task<int> registrar_pedidoAsync(int codigo_farmacia, int codigo_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelar_pedido", ReplyAction="*")]
        bool cancelar_pedido(int id_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cancelar_pedido", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> cancelar_pedidoAsync(int id_compra);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_cliente", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_clienteRequestBody Body;
        
        public consultar_clienteRequest() {
        }
        
        public consultar_clienteRequest(Farmacia_.Servicio.consultar_clienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_clienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nit;
        
        public consultar_clienteRequestBody() {
        }
        
        public consultar_clienteRequestBody(string nit) {
            this.nit = nit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_clienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_clienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_clienteResponseBody Body;
        
        public consultar_clienteResponse() {
        }
        
        public consultar_clienteResponse(Farmacia_.Servicio.consultar_clienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_clienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Farmacia_.Servicio.cliente consultar_clienteResult;
        
        public consultar_clienteResponseBody() {
        }
        
        public consultar_clienteResponseBody(Farmacia_.Servicio.cliente consultar_clienteResult) {
            this.consultar_clienteResult = consultar_clienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_medicamentosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_medicamentos", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_medicamentosRequestBody Body;
        
        public consultar_medicamentosRequest() {
        }
        
        public consultar_medicamentosRequest(Farmacia_.Servicio.consultar_medicamentosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_medicamentosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigo_farmacia;
        
        public consultar_medicamentosRequestBody() {
        }
        
        public consultar_medicamentosRequestBody(int codigo_farmacia) {
            this.codigo_farmacia = codigo_farmacia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_medicamentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_medicamentosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_medicamentosResponseBody Body;
        
        public consultar_medicamentosResponse() {
        }
        
        public consultar_medicamentosResponse(Farmacia_.Servicio.consultar_medicamentosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_medicamentosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Farmacia_.Servicio.ArrayOfMedicamento consultar_medicamentosResult;
        
        public consultar_medicamentosResponseBody() {
        }
        
        public consultar_medicamentosResponseBody(Farmacia_.Servicio.ArrayOfMedicamento consultar_medicamentosResult) {
            this.consultar_medicamentosResult = consultar_medicamentosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_farmaciasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_farmacias", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_farmaciasRequestBody Body;
        
        public consultar_farmaciasRequest() {
        }
        
        public consultar_farmaciasRequest(Farmacia_.Servicio.consultar_farmaciasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultar_farmaciasRequestBody {
        
        public consultar_farmaciasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_farmaciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_farmaciasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_farmaciasResponseBody Body;
        
        public consultar_farmaciasResponse() {
        }
        
        public consultar_farmaciasResponse(Farmacia_.Servicio.consultar_farmaciasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_farmaciasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Farmacia_.Servicio.ArrayOfFarmacia consultar_farmaciasResult;
        
        public consultar_farmaciasResponseBody() {
        }
        
        public consultar_farmaciasResponseBody(Farmacia_.Servicio.ArrayOfFarmacia consultar_farmaciasResult) {
            this.consultar_farmaciasResult = consultar_farmaciasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_clientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_clientes", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_clientesRequestBody Body;
        
        public consultar_clientesRequest() {
        }
        
        public consultar_clientesRequest(Farmacia_.Servicio.consultar_clientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class consultar_clientesRequestBody {
        
        public consultar_clientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_clientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_clientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_clientesResponseBody Body;
        
        public consultar_clientesResponse() {
        }
        
        public consultar_clientesResponse(Farmacia_.Servicio.consultar_clientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_clientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Farmacia_.Servicio.ArrayOfCliente consultar_clientesResult;
        
        public consultar_clientesResponseBody() {
        }
        
        public consultar_clientesResponseBody(Farmacia_.Servicio.ArrayOfCliente consultar_clientesResult) {
            this.consultar_clientesResult = consultar_clientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_pedidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_pedidos", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_pedidosRequestBody Body;
        
        public consultar_pedidosRequest() {
        }
        
        public consultar_pedidosRequest(Farmacia_.Servicio.consultar_pedidosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_pedidosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigo_farmacia;
        
        public consultar_pedidosRequestBody() {
        }
        
        public consultar_pedidosRequestBody(int codigo_farmacia) {
            this.codigo_farmacia = codigo_farmacia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultar_pedidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultar_pedidosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.consultar_pedidosResponseBody Body;
        
        public consultar_pedidosResponse() {
        }
        
        public consultar_pedidosResponse(Farmacia_.Servicio.consultar_pedidosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultar_pedidosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Farmacia_.Servicio.ArrayOfPedido consultar_pedidosResult;
        
        public consultar_pedidosResponseBody() {
        }
        
        public consultar_pedidosResponseBody(Farmacia_.Servicio.ArrayOfPedido consultar_pedidosResult) {
            this.consultar_pedidosResult = consultar_pedidosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrar_compraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar_compra", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.registrar_compraRequestBody Body;
        
        public registrar_compraRequest() {
        }
        
        public registrar_compraRequest(Farmacia_.Servicio.registrar_compraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrar_compraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codigo_tienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int codigo_cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Farmacia_.Servicio.ArrayOfInt codigo_productos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Farmacia_.Servicio.ArrayOfInt unidades_productos;
        
        public registrar_compraRequestBody() {
        }
        
        public registrar_compraRequestBody(int codigo_tienda, int codigo_cliente, Farmacia_.Servicio.ArrayOfInt codigo_productos, Farmacia_.Servicio.ArrayOfInt unidades_productos) {
            this.codigo_tienda = codigo_tienda;
            this.codigo_cliente = codigo_cliente;
            this.codigo_productos = codigo_productos;
            this.unidades_productos = unidades_productos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrar_compraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar_compraResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.registrar_compraResponseBody Body;
        
        public registrar_compraResponse() {
        }
        
        public registrar_compraResponse(Farmacia_.Servicio.registrar_compraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrar_compraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Farmacia_.Servicio.ArrayOfInt registrar_compraResult;
        
        public registrar_compraResponseBody() {
        }
        
        public registrar_compraResponseBody(Farmacia_.Servicio.ArrayOfInt registrar_compraResult) {
            this.registrar_compraResult = registrar_compraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrar_clienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar_cliente", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.registrar_clienteRequestBody Body;
        
        public registrar_clienteRequest() {
        }
        
        public registrar_clienteRequest(Farmacia_.Servicio.registrar_clienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrar_clienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string direccion;
        
        public registrar_clienteRequestBody() {
        }
        
        public registrar_clienteRequestBody(string nit, string nombre, string apellido, string telefono, string direccion) {
            this.nit = nit;
            this.nombre = nombre;
            this.apellido = apellido;
            this.telefono = telefono;
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrar_clienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar_clienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Farmacia_.Servicio.registrar_clienteResponseBody Body;
        
        public registrar_clienteResponse() {
        }
        
        public registrar_clienteResponse(Farmacia_.Servicio.registrar_clienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrar_clienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int registrar_clienteResult;
        
        public registrar_clienteResponseBody() {
        }
        
        public registrar_clienteResponseBody(int registrar_clienteResult) {
            this.registrar_clienteResult = registrar_clienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Farmacia_.Servicio.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Farmacia_.Servicio.Service1Soap>, Farmacia_.Servicio.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Servicio.consultar_clienteResponse Farmacia_.Servicio.Service1Soap.consultar_cliente(Farmacia_.Servicio.consultar_clienteRequest request) {
            return base.Channel.consultar_cliente(request);
        }
        
        public Farmacia_.Servicio.cliente consultar_cliente(string nit) {
            Farmacia_.Servicio.consultar_clienteRequest inValue = new Farmacia_.Servicio.consultar_clienteRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_clienteRequestBody();
            inValue.Body.nit = nit;
            Farmacia_.Servicio.consultar_clienteResponse retVal = ((Farmacia_.Servicio.Service1Soap)(this)).consultar_cliente(inValue);
            return retVal.Body.consultar_clienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_clienteResponse> Farmacia_.Servicio.Service1Soap.consultar_clienteAsync(Farmacia_.Servicio.consultar_clienteRequest request) {
            return base.Channel.consultar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_clienteResponse> consultar_clienteAsync(string nit) {
            Farmacia_.Servicio.consultar_clienteRequest inValue = new Farmacia_.Servicio.consultar_clienteRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_clienteRequestBody();
            inValue.Body.nit = nit;
            return ((Farmacia_.Servicio.Service1Soap)(this)).consultar_clienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Servicio.consultar_medicamentosResponse Farmacia_.Servicio.Service1Soap.consultar_medicamentos(Farmacia_.Servicio.consultar_medicamentosRequest request) {
            return base.Channel.consultar_medicamentos(request);
        }
        
        public Farmacia_.Servicio.ArrayOfMedicamento consultar_medicamentos(int codigo_farmacia) {
            Farmacia_.Servicio.consultar_medicamentosRequest inValue = new Farmacia_.Servicio.consultar_medicamentosRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_medicamentosRequestBody();
            inValue.Body.codigo_farmacia = codigo_farmacia;
            Farmacia_.Servicio.consultar_medicamentosResponse retVal = ((Farmacia_.Servicio.Service1Soap)(this)).consultar_medicamentos(inValue);
            return retVal.Body.consultar_medicamentosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_medicamentosResponse> Farmacia_.Servicio.Service1Soap.consultar_medicamentosAsync(Farmacia_.Servicio.consultar_medicamentosRequest request) {
            return base.Channel.consultar_medicamentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_medicamentosResponse> consultar_medicamentosAsync(int codigo_farmacia) {
            Farmacia_.Servicio.consultar_medicamentosRequest inValue = new Farmacia_.Servicio.consultar_medicamentosRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_medicamentosRequestBody();
            inValue.Body.codigo_farmacia = codigo_farmacia;
            return ((Farmacia_.Servicio.Service1Soap)(this)).consultar_medicamentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Servicio.consultar_farmaciasResponse Farmacia_.Servicio.Service1Soap.consultar_farmacias(Farmacia_.Servicio.consultar_farmaciasRequest request) {
            return base.Channel.consultar_farmacias(request);
        }
        
        public Farmacia_.Servicio.ArrayOfFarmacia consultar_farmacias() {
            Farmacia_.Servicio.consultar_farmaciasRequest inValue = new Farmacia_.Servicio.consultar_farmaciasRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_farmaciasRequestBody();
            Farmacia_.Servicio.consultar_farmaciasResponse retVal = ((Farmacia_.Servicio.Service1Soap)(this)).consultar_farmacias(inValue);
            return retVal.Body.consultar_farmaciasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_farmaciasResponse> Farmacia_.Servicio.Service1Soap.consultar_farmaciasAsync(Farmacia_.Servicio.consultar_farmaciasRequest request) {
            return base.Channel.consultar_farmaciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_farmaciasResponse> consultar_farmaciasAsync() {
            Farmacia_.Servicio.consultar_farmaciasRequest inValue = new Farmacia_.Servicio.consultar_farmaciasRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_farmaciasRequestBody();
            return ((Farmacia_.Servicio.Service1Soap)(this)).consultar_farmaciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Servicio.consultar_clientesResponse Farmacia_.Servicio.Service1Soap.consultar_clientes(Farmacia_.Servicio.consultar_clientesRequest request) {
            return base.Channel.consultar_clientes(request);
        }
        
        public Farmacia_.Servicio.ArrayOfCliente consultar_clientes() {
            Farmacia_.Servicio.consultar_clientesRequest inValue = new Farmacia_.Servicio.consultar_clientesRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_clientesRequestBody();
            Farmacia_.Servicio.consultar_clientesResponse retVal = ((Farmacia_.Servicio.Service1Soap)(this)).consultar_clientes(inValue);
            return retVal.Body.consultar_clientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_clientesResponse> Farmacia_.Servicio.Service1Soap.consultar_clientesAsync(Farmacia_.Servicio.consultar_clientesRequest request) {
            return base.Channel.consultar_clientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_clientesResponse> consultar_clientesAsync() {
            Farmacia_.Servicio.consultar_clientesRequest inValue = new Farmacia_.Servicio.consultar_clientesRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_clientesRequestBody();
            return ((Farmacia_.Servicio.Service1Soap)(this)).consultar_clientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Servicio.consultar_pedidosResponse Farmacia_.Servicio.Service1Soap.consultar_pedidos(Farmacia_.Servicio.consultar_pedidosRequest request) {
            return base.Channel.consultar_pedidos(request);
        }
        
        public Farmacia_.Servicio.ArrayOfPedido consultar_pedidos(int codigo_farmacia) {
            Farmacia_.Servicio.consultar_pedidosRequest inValue = new Farmacia_.Servicio.consultar_pedidosRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_pedidosRequestBody();
            inValue.Body.codigo_farmacia = codigo_farmacia;
            Farmacia_.Servicio.consultar_pedidosResponse retVal = ((Farmacia_.Servicio.Service1Soap)(this)).consultar_pedidos(inValue);
            return retVal.Body.consultar_pedidosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_pedidosResponse> Farmacia_.Servicio.Service1Soap.consultar_pedidosAsync(Farmacia_.Servicio.consultar_pedidosRequest request) {
            return base.Channel.consultar_pedidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Servicio.consultar_pedidosResponse> consultar_pedidosAsync(int codigo_farmacia) {
            Farmacia_.Servicio.consultar_pedidosRequest inValue = new Farmacia_.Servicio.consultar_pedidosRequest();
            inValue.Body = new Farmacia_.Servicio.consultar_pedidosRequestBody();
            inValue.Body.codigo_farmacia = codigo_farmacia;
            return ((Farmacia_.Servicio.Service1Soap)(this)).consultar_pedidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Servicio.registrar_compraResponse Farmacia_.Servicio.Service1Soap.registrar_compra(Farmacia_.Servicio.registrar_compraRequest request) {
            return base.Channel.registrar_compra(request);
        }
        
        public Farmacia_.Servicio.ArrayOfInt registrar_compra(int codigo_tienda, int codigo_cliente, Farmacia_.Servicio.ArrayOfInt codigo_productos, Farmacia_.Servicio.ArrayOfInt unidades_productos) {
            Farmacia_.Servicio.registrar_compraRequest inValue = new Farmacia_.Servicio.registrar_compraRequest();
            inValue.Body = new Farmacia_.Servicio.registrar_compraRequestBody();
            inValue.Body.codigo_tienda = codigo_tienda;
            inValue.Body.codigo_cliente = codigo_cliente;
            inValue.Body.codigo_productos = codigo_productos;
            inValue.Body.unidades_productos = unidades_productos;
            Farmacia_.Servicio.registrar_compraResponse retVal = ((Farmacia_.Servicio.Service1Soap)(this)).registrar_compra(inValue);
            return retVal.Body.registrar_compraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Servicio.registrar_compraResponse> Farmacia_.Servicio.Service1Soap.registrar_compraAsync(Farmacia_.Servicio.registrar_compraRequest request) {
            return base.Channel.registrar_compraAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Servicio.registrar_compraResponse> registrar_compraAsync(int codigo_tienda, int codigo_cliente, Farmacia_.Servicio.ArrayOfInt codigo_productos, Farmacia_.Servicio.ArrayOfInt unidades_productos) {
            Farmacia_.Servicio.registrar_compraRequest inValue = new Farmacia_.Servicio.registrar_compraRequest();
            inValue.Body = new Farmacia_.Servicio.registrar_compraRequestBody();
            inValue.Body.codigo_tienda = codigo_tienda;
            inValue.Body.codigo_cliente = codigo_cliente;
            inValue.Body.codigo_productos = codigo_productos;
            inValue.Body.unidades_productos = unidades_productos;
            return ((Farmacia_.Servicio.Service1Soap)(this)).registrar_compraAsync(inValue);
        }
        
        public int registrar_pago(int codigo_compra, int tipo_pago) {
            return base.Channel.registrar_pago(codigo_compra, tipo_pago);
        }
        
        public System.Threading.Tasks.Task<int> registrar_pagoAsync(int codigo_compra, int tipo_pago) {
            return base.Channel.registrar_pagoAsync(codigo_compra, tipo_pago);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Farmacia_.Servicio.registrar_clienteResponse Farmacia_.Servicio.Service1Soap.registrar_cliente(Farmacia_.Servicio.registrar_clienteRequest request) {
            return base.Channel.registrar_cliente(request);
        }
        
        public int registrar_cliente(string nit, string nombre, string apellido, string telefono, string direccion) {
            Farmacia_.Servicio.registrar_clienteRequest inValue = new Farmacia_.Servicio.registrar_clienteRequest();
            inValue.Body = new Farmacia_.Servicio.registrar_clienteRequestBody();
            inValue.Body.nit = nit;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.telefono = telefono;
            inValue.Body.direccion = direccion;
            Farmacia_.Servicio.registrar_clienteResponse retVal = ((Farmacia_.Servicio.Service1Soap)(this)).registrar_cliente(inValue);
            return retVal.Body.registrar_clienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Farmacia_.Servicio.registrar_clienteResponse> Farmacia_.Servicio.Service1Soap.registrar_clienteAsync(Farmacia_.Servicio.registrar_clienteRequest request) {
            return base.Channel.registrar_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Farmacia_.Servicio.registrar_clienteResponse> registrar_clienteAsync(string nit, string nombre, string apellido, string telefono, string direccion) {
            Farmacia_.Servicio.registrar_clienteRequest inValue = new Farmacia_.Servicio.registrar_clienteRequest();
            inValue.Body = new Farmacia_.Servicio.registrar_clienteRequestBody();
            inValue.Body.nit = nit;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.telefono = telefono;
            inValue.Body.direccion = direccion;
            return ((Farmacia_.Servicio.Service1Soap)(this)).registrar_clienteAsync(inValue);
        }
        
        public int registrar_pedido(int codigo_farmacia, int codigo_compra) {
            return base.Channel.registrar_pedido(codigo_farmacia, codigo_compra);
        }
        
        public System.Threading.Tasks.Task<int> registrar_pedidoAsync(int codigo_farmacia, int codigo_compra) {
            return base.Channel.registrar_pedidoAsync(codigo_farmacia, codigo_compra);
        }
        
        public bool cancelar_pedido(int id_compra) {
            return base.Channel.cancelar_pedido(id_compra);
        }
        
        public System.Threading.Tasks.Task<bool> cancelar_pedidoAsync(int id_compra) {
            return base.Channel.cancelar_pedidoAsync(id_compra);
        }
    }
}
